### PR TITLE
feat: .NET 9 support

### PR DESCRIPTION
**Pull request by skolmer**
# Description

This PR adds support for .NET 9.

Npgsql.EntityFrameworkCore.PostgreSQL is not released yet so I had to reference 9.0.0-rc.2 in the tests.

### CODE REVIEW

**Review by alirezanet — APPROVED** [review]
Awesome thanks 👌

**Comment by k94ll13nn3** [comment]
Hello @alirezanet, do you have an ETA on when the package will be available on NuGet?

**Comment by alirezanet** [comment]
hi @k94ll13nn3,
I'll release it soon, tonight if I have time, or until the end of this week

**Comment by alirezanet** [comment]
Hi @k94ll13nn3,
I just released `v2.15.1` with dotnet 9 support

**Pull request merged**
