### PR TITLE
Child element property query

### PR DESCRIPTION
**Pull request by sunyuliang**
Add sub attribute query, such as `Role.Name=*Mana`

### CODE REVIEW

**Comment by alirezanet** [comment]
> Add sub attribute query, such as `Role.Name=*Mana`

You can achieve that simply with a custom mapper or query builder.

e.g
```c#
var builder = new QueryBuilder<User>()
			.AddMap("roleName" , q => q.Role.Name)
			.AddCondition("roleName=*Mana");
```
If this doesn't solve your problem you should explain a little more.

**Comment by alirezanet** [comment]
Nice idea!
But how we can exclude some child properties, using this feature? for example, one common problem is excluding filtering capabilities on some properties like `password`. we don't want to let users use filtering with the password props.

In these situations, gridify offers a custom mapper that you have full control over mappings.
I think one option to solve this could be adding configuration settings to turn it on/off (globally and mapper level)

**Comment by alirezanet** [comment]
Also, you should add some documentation about your feature in Docs.
thanks

**Comment by sunyuliang** [comment]
Hello,
if we need to judge such a LINQ expression:

`u.Role!= null&&u.Role. Company!= null&&u.Role. Company. Name=="Compnay"`

If sub attributes are not supported, the usage is as follows:

```
new QueryBuilder<User>()

.AddMap("Role", q => q.Role)

.AddMap("Role_Company", q => q.Role.Company)

.AddMap("Role_Company_Name", q => q.Role.Company.Name)

.AddCondition("Role!=null,Role_Company!=null,Role_Company_Name=Compnay")
```
If sub attributes are supported, you can directly use the following:

```
new QueryBuilder<User>()
.AddCondition("Role!=null,Role.Company!=null,Role.Company.Name=Compnay")
```

Or:

`Users.ApplyFiltering("Role!=null,Role.Company!=null,Role.Company.Name=Compnay")`

It can be seen from the above that more mappings need to be configured, and the naming is quite different from the native LINQ. I think the default expression should be as simple and flexible as possible and consistent with the native LINQ. The attributes of subclasses can be directly used in the native LINQ. Therefore, it is better for gridify to directly support the attributes of subclasses by default.


If you want to mask sub attributes, you can use gridifymapper as described on the official website.

GridifyMapper. Generatemappings does not generate attribute mappings for subclasses, nor can it generate subclasses, otherwise circular references may occur.

**Comment by sunyuliang** [comment]
Hi:


&nbsp;&nbsp;roleName=*Mana,


If role is null, this expression throws an exception




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alirezanet/Gridify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月26日(星期天) 凌晨3:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alirezanet/Gridify] Child element property query (PR #60)





  
Add sub attribute query, such as Role.Name=*Mana
  
You can achieve that simply with a custom mapper or query builder.
 
e.g
 var builder = new QueryBuilder<User&gt;() 			.AddMap("roleName" , q =&gt; q.Role.Name) 			.AddCondition("roleName=*Mana");
 
If this doesn't solve your problem you should explain a little more.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alirezanet** [comment]
Hi, I totally agree this feature is great.

My first comment (that I immediately removed) was because I didn't realize this is a **pull request** I taught you asking how we can do it and this is an issue. (my bad) 

----

But still, we should solve some problems before releasing this feature 

1. We need to provide a new configuration to Enable/Disable this functionality. In the global configurations, it can be Enabled by default to handle your expected behavior as you described, but in the custom mappers, it must be disabled by default. the reason is, this can cause a lot of security problems because the end-user can access the sub-classes even when creating a custom mapper.
2. We need some unit tests to check if it's working with sub-collection and indexes.
3. We should add the corresponding documentations.

I can merge your PL in the `next` branch and work on the above problems or keep the PL open and let you add solve it, 
Let me know which are you more comfortable with?

**Comment by sunyuliang** [comment]
I'd better wait for you to update. My consideration should still be one-sided.Thank you.

**Comment by alirezanet** [comment]
Sure, Thanks for your contribution.

**Pull request merged**
